server.port: 8888

# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info
    lab.org: DEBUG
spring:
  cloud:
    config:
      server:
        git:
          uri: file:/config-repo

---
spring.config.activate.on-profile: docker
spring.cloud.config.server.: file:/config-repo
