#spring.config.import: "configserver:"
#
#spring:
#  application.name: auth-server
#  cloud.config:
#    failFast: true
#    retry:
#      initialInterval: 3000
#      multiplier: 1.3
#      maxInterval: 10000
#      maxAttempts: 20
#    uri: http://localhost:8888
#    username: ${CONFIG_SERVER_USR}
#    password: ${CONFIG_SERVER_PWD}
#
#---
#spring.config.activate.on-profile: docker
#
#spring.cloud.config.uri: http://config-server:8888



server.port: 9999
server.forward-headers-strategy: framework

spring.application.name: auth-server

app:
  eureka-username: u
  eureka-password: p
  eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO

---
spring.config.activate.on-profile: docker

app.eureka-server: eureka
